name: Daily Commit

on:
  schedule:
    - cron: '30 3 * * *'  # Runs daily at 03:30 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Add Daily Commit (23ds2000055@ds.study.iitm.ac.in)
        run: |
          echo "$(date)" >> daily_commit_log.txt  # Append timestamp
          git config --global user.name "GitHub Actions"
          git config --global user.email "23ds2000055@ds.study.iitm.ac.in"
          git add daily_commit_log.txt
          git commit -m "Daily commit - $(date)"
          git push
